inputs_def:
  - handle: df
    description: Input
    json_schema:
      contentMediaType: oomol/var
outputs_def:
  []
ui:
  default_width: 450
executor:
  name: python
  options:
    spawn: false
    entry: __init__.py
title: DF Preview
description: "This block is used to preview and display DataFrame data in a tabular format"
icon: ":carbon:table-split:"
