ui:
  default_width: 450
inputs_def:
  - handle: geological_data
    description: Input
    json_schema:
      type: string
outputs_def:
  - handle: df
    description: Output
    json_schema:
      contentMediaType: oomol/var
executor:
  name: python
  options:
    entry: __init__.py
    spawn: false
description: Preview charts using Scriptlets
icon: ":carbon:chart-area:"
