ui:
  default_width: 450
inputs_def:
  - handle: geological_data
    description: Input
    json_schema:
      type: string
outputs_def:
  - handle: df
    description: Output
    json_schema:
      contentMediaType: oomol/var
executor:
  name: python
  options:
    entry: __init__.py
    spawn: false
description: "This block is used to preview and display charts from geological
  data using interactive scriptlets"
icon: ":carbon:chart-area:"
