inputs_def:
  - handle: image
    description: Input
    json_schema:
      type: string
      ui:widget: file
outputs_def:
  - handle: output
    json_schema:
      type: string
ui:
  default_width: 450
executor:
  name: nodejs
  options:
    spawn: false
    entry: main.ts
title: Image Preview
icon: ":fa6-solid:image:"
